language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"
matrix:
    allow_failures:
        - python: "nightly"
before_install:
    - pip install poetry
    - poetry install
script:
    - make check
